### ISSUE TITLE
RELEASE 1.36.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1054]
### Changelog

New features:
- Increase size limit to show document preview from 10mb to 20mb #1056
- Backend theme tweaks #1073
- Page Builder: Hide Revisions when Page Builder is active #1072 
- Page Builder: Hide new buttons #1071

Bugfixes:
- Edit iframe embed widget view is blank #1069
- SR Employees: table option in wysiwyg broken #1070 
- Embedded dashboard displays mysites #1055 (Hotfix 1.35.3)

Hotfixes since previous release
- Hotfix 1.35.1: Accessibility updates (wp-proud-theme), with Release 1.35.0
- Hotfix 1.35.2: Fixing degredation with non-elasticsearch searches (wp-proud-search), July 26
- Hotfix 1.35.2: Fixing degredation with non-elasticsearch searches (wp-proud-search), July 26
- Hotfix 1.35.3: Embedded Dashboard showing All Sites (wp-proud-core), #1055 July 27

WordPress Core Update 
- WordPress Core was upgraded from 4.8.0 to 4.8.1 in this release. [WordPress 4.8.1](https://wordpress.org/news/2017/08/wordpress-4-8-1-maintenance-release/) is a minor maintenance release.

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/a8eec84261bb3cacdaf924bf65c1ab5677602f81)
- wp-stateless 1.9.0 -> 1.9.2
- wordpress-seo 5.1 -> 5.2
- siteorigin-panels 2.5.8 -> 2.5.10
- so-widgets-bundle 1.9.5  -> 1.9.6
- wp-job-manager 1.27.0 -> 1.28.0
- simple-staff-list 1.19 -> 2.0.1
- broken-link-checker 1.11.3  -> 1.11.5

### Scripted updates
```
wp search-replace WP_Widget_Text ProudEmbed --allow-root
```
### Manual updates
- [x] We will also need to import the layout template from http://localhost:8000/wp-admin/post.php?post=2762&action=edit into PO: https://www.cityofportorchard.us/wp-admin/post.php?post=2992&action=edit #1069
- [x] RM popupmaker from SR Parks kube sites ENV vars #1061

### Testing emphasis
- [x] login from my.proudcity.com
- [x] login redirect
- [x] Responsive imgs
- [x] Login
- [x] Gravityforms
- [x] Search
- [x] #1069
- [x] Test livelifelocally.org popup background div
- [x] Beta: check /iframe1, /iframe2
- [x] SR Employees: table option in wysiwyg broken #1070
- [x] Update SR theme version + SR Parks + Beta?
- [x] Check https://www.westcarrollton.org/residents/

**Comment by jlyon** [comment]
Pushed, posted, sent @dluke @kevindherman @lukefretwell  @aschmoe .

I want to try to clean up github/waffle, so I. added an item to the after meetings next week:
- Cleaning up Waffle (Pending Close col, using Queued more, In Progress less)

**Comment by jlyon** [comment]
@kevindherman there was an issue with SR images that I fixed manually. It looks like they were the only  site affected.
