### ISSUE TITLE
Release 1.39.0

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#1121]
### Changelog

New features:
- Improve, add additional alert bar colors #1114 
- Background color options #1110 (Hotfix 1.38.2)
- Upgrade wp-stateless to 2.0.1 #1099 

Bugfixes:
- Make file upload limit 25MB
- Disabling full screen map does not work #1116 

Hotfixes since previous release
- Hotfix 1.38.1: Remove Kiosk updates to theme (wp-proud-theme), with Release 1.38.0
- Hotfix 1.38.2: Background color options (wp-proud-theme) #1110

WordPress Core Update 
- The [WordPress Core 4.8.2 security and maintenance update](https://wordpress.org/news/2017/09/wordpress-4-8-2-security-and-maintenance-release/) is included in this release. This is almost entirely a security release and there should no noticeable changes to your ProudCity implementation.

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/4d077404cb476a6c749a3478bc2026bbe6148d3e)
* wp-stateless: 1.9.2 -> 2.1.0
* wordpress-seo: 5.4 -> 5.4.2
* siteorigin-panels: 2.5.11 -> 2.5.12
* so-widgets-bundle: 1.9.9 -> 1.9.10

### Scripted updates
```
# @todo: do we want to run this?
# Change all /wp-content/uploads/ references to GCE
wp search-replace $(wp option get siteurl --allow-root)/wp-content/uploads/ https://storage.googleapis.com/proudcity/${STATELESS_MEDIA_DIRECTORY} --allow-root
```
### Testing emphasis
- [x] login from my.proudcity.com
- [x] login redirect
- [ ] Responsive imgs
- [ ] Login
- [ ] Gravityforms
- [ ] Search
- [ ] Look at SR images
- [x] Max filesize #1096
-  [x] wp-stateless (upgraded from 1.x to 2.x) @aschmoe  !! #1999
- [x] upload max filesize #1122

**Comment by jlyon** [comment]
Pushed posted and sent @kevindherman @lukefretwell @aschmoe.

I added in an extra section to spell out the file upload changes.

Sorry, we didn't get to all of the issues you included, @kevindherman.  We should have a pretty big hotfix release tomorrow.

**Comment by kevindherman** [comment]
@jlyon @aschmoe awesome job. I'm thrilled about the background color, alert bar options and making progress on file size issue. 

Sounds good on the hot fixes.

cc @lukefretwell
