### ISSUE TITLE
RELEASE 1.40.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1125]
## Changelog

New features:
- Add pc-cli, a command-line too for partners to quickly spin up a local development environment #1135
- Hotfix 1.39.3: Making navbar have dynamic width (wp-proud-theme) #942

Bugfixes:
- Form formatting: field labels for radio lists #1138
- Hotfix 1.39.1: Default value for full screen map overwritten (wp-proud-map-app) #1116, with Release 1.39.0
- Hotfix 1.39.2: Fixing screen map overwritten (wp-proud-map-app, wp-proud-core) #1116
- Hotfix 1.39.4: Google translate creates gap (wp-proud-theme) #1131
- Hotfix 1.39.5: Dropdown menus broken after release (wp-proud-theme) #1132

Hotfixes since previous release
- Hotfix 1.39.1: Default value for full screen map overwritten (wp-proud-map-app) #1116, with Release 1.39.0
- Hotfix 1.39.2: Fixing screen map overwritten (wp-proud-map-app, wp-proud-core) #1116
- Hotfix 1.39.3: Making navbar have dynamic width (wp-proud-theme) #942
- Hotfix 1.39.4: Google translate creates gap (wp-proud-theme) #1131
- Hotfix 1.39.5: Dropdown menus broken after release (wp-proud-theme) #1132

WordPress Core Update 
- There is no WordPress Core update in this release.

3rd party plugin updates (8de854e57b2a4a3a08b7e5132db5779bfdb948bd)
- wordpress-seo 5.4.2 -> 5.5.1
- siteorigin-panels 2.5.12 -> 2.5.13
- wp-job-manager 1.28.0 -> 1.29.0

### Scripted updates
```
# @todo: do we want to run this?
# Change all /wp-content/uploads/ references to GCE
wp search-replace $(wp option get siteurl --allow-root)/wp-content/uploads/ https://storage.googleapis.com/proudcity/${STATELESS_MEDIA_DIRECTORY} --allow-root
```
### Testing emphasis
- [ ] login from my.proudcity.com
- [ ] login redirect
- [ ] Responsive imgs
- [ ] Login
- [ ] Gravityforms
- [ ] Search
- [ ] Look at SR images
- [ ] Max filesize #1096
-  [ ] wp-stateless (upgraded from 1.x to 2.x) @aschmoe  !! #1999
- [ ] upload max filesize #1122
- [ ] Auth0 #1139

**Comment by jlyon** [comment]
Pushed, posted and sent @kevindherman @lukefretwell @aschmoe.

I added all of the users that had accounts with us, but weren't in Mailchimp (57 emails) @kevindherman.
