### ISSUE TITLE
RELEASE 1.41.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1140]
## Changelog

New features:
- Add min-height to actions box #1128
- Allow job posting display customizations #1143
- Allow Staff directory to be used for a list of resources #1156 #1157 
- Accessibility enhancement: Google translate needs label for accessibility #1158 
- Language: Allow Payments to be overwritten to "Donations"

Bugfixes:
- Menu edit page: Hide Display Location #1154 
- Hotfix 1.40.2: Remove unnecessary items from HEAD (wp-proud-core) #1142
- Infrastructure: Password protection: Breaks sp-cli #1141
- Hotfix 1.40.1: Re-enable redirect from Dashboard login links (wp-auth0) #1139, with Release 1.40.0
- Issues logging in from /wp-admin and with accounts that are both u/p AND Google #1139 
- Dashboard: Fix Analytics settings link https://github.com/proudcity/proudcity-dashboard/issues/37
 - Dashboard: When deleting user: Don't delete content https://github.com/proudcity/proudcity-dashboard/issues/38

Hotfixes since previous release
- Hotfix 1.40.1: Re-enable redirect from Dashboard login links (wp-auth0) #1139, with Release 1.40.0
- Hotfix 1.40.2: Remove unnecessary items from HEAD (wp-proud-core) #1142

WordPress Core Update 
- There is no WordPress Core update in this release.

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/a13e0d21b4da420b15822e6d32f31542279c0bd1)
- wordpress-seo 5.5.1 -> 5.6.1
- so-widgets-bundle 1.9.10 -> 1.10.1

### Scripted updates
```
# @todo: do we want to run this?
# Change all /wp-content/uploads/ references to GCE
wp search-replace $(wp option get siteurl --allow-root)/wp-content/uploads/ https://storage.googleapis.com/proudcity/${STATELESS_MEDIA_DIRECTORY} --allow-root
```
### Testing emphasis
- [x] login from my.proudcity.com
- [x] login redirect
- [x] Responsive imgs
- [x] Login
- [x] Gravityforms
- [x] Search
- [x] Look at SR images
- [x] Max filesize #1096
-  [x] wp-stateless (upgraded from 1.x to 2.x) @aschmoe  !! #1999
- [x] upload max filesize #1122
- [x] Auth0 #1139

**Comment by jlyon** [comment]
Pushed, posted and sent @lukefretwell @kevindherman @aschmoe
