### ISSUE TITLE
RELEASE 1.42.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1159]
## Changelog

New features:
- Preview Office files in Microsoft Online viewer, other files in Google Docs viewer #1170
- Service center: make placeholder match tabs #1173 
- Service center Kiosk launch #1160 

Bugfixes:
- Event detail doesn't display end time #1115 

Hotfixes since previous release
- Hotfix 1.41.1: Kiosk Launch (wp-proud-actions-app, wp-proud-sr-ca-theme) #1160
- Hotfix 1.41.2: WordPress Core security update 4.8.3 #1171, 2017-10-30

WordPress Core Update 
- WordPress Core security update 4.8.3 was appled as Hotfix 1.41.2 the day it was released on October 30 2017.

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/01c073cd56003adc9a7187ee52395e4986af4064)
- wordpress-seo 5.6.1 -> 5.7.1
- wp-mail-smtp 0.10.1 -> 0.11.1
- so-widgets-bundle 1.10.1 -> 1.10.2
- elasticpress 2.3.2 -> 2.4

### Scripted updates
```
# @todo: do we want to run this?
# Change all /wp-content/uploads/ references to GCE
wp search-replace $(wp option get siteurl --allow-root)/wp-content/uploads/ https://storage.googleapis.com/proudcity/${STATELESS_MEDIA_DIRECTORY} --allow-root
```
### Testing emphasis
- [x] login from my.proudcity.com
- [x] login redirect
- [x] Responsive imgs
- [x] Login
- [x] Gravityforms
- [x] Search
- [x] Look at SR images
- [x] Auth0 #1139
- [x] Follow up #1170 office viewer

**Comment by jlyon** [comment]
Pushed posted and sent @lukefretwell @kevindherman @aschmoe
