### ISSUE TITLE
RELEASE 1.43.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1176]
## Changelog

New features:
- Kiosk: Directory: Add Content field https://github.com/proudcity/proudcity-dashboard/issues/45
- Increase test site file upload maxsize #1146
- Add to example: Media Folders #1174 

Bugfixes:
- Document preview broken (Hotfixes 1.42.1, 1.42.2)
- Add cache-busing to wp-proud-actions-app #1179 
- Post date format for documents (add comma) #1147 

Hotfixes since previous release
- Hotfix 1.42.1: Document preview broken #1177 (wp-proud-theme) Nov 2 2017
- Hotfix 1.42.2: Document preview broken #1177 (wp-proud-theme) Nov 2 2017
- Hotfix 1.42.3: Add cache-busing to JS assets #1147 (wp-proud-actions-app); Add flag to require Wordpress account to access Intranet (wp-proudcity); Post date format for documents (add comma) #1147 (wp-proud-theme) Nov 9 2017
- Hotfix 1.42.4: Moving authentication checking code into wp-proud-code (out of wp-config.php https://github.com/proudcity/proudcity-dashboard/issues/30  (wp-proud-core) Nov 9 2017

WordPress Core Update 
- WordPress Core was updated to version 4.9 in this release. Read all about the WordPress Tipton Release on the [WordPress blog](https://wordpress.org/news/2017/11/tipton/).

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/78a1a0a9401fc9674b67c81a1840b1ebb353e764)
- wordpress-seo 5.7.1 -> 5.8
- admin-menu-editor 1.8 -> 1.8.1
- siteorigin-panels 2.5.13 -> 2.5.14
- so-widgets-bundle 1.10.2 -> 1.11.0
- events-manager 5.7.3 -> 5.8.1

### Scripted updates
```
# @todo: do we want to run this?
# Change all /wp-content/uploads/ references to GCE
wp search-replace $(wp option get siteurl --allow-root)/wp-content/uploads/ https://storage.googleapis.com/proudcity/${STATELESS_MEDIA_DIRECTORY} --allow-root
```
### Testing emphasis
- [x] login from my.proudcity.com
- [x] login redirect
- [ ] Responsive imgs
- [x] Login
- [x] Gravityforms
- [x] Search
- [x] Look at SR images
- [x] Auth0 #1139
- [x] Follow up #1170 office viewer

**Comment by jlyon** [comment]
Pushed posted and send @kevindherman @lukefretwell @aschmoe
