### ISSUE TITLE
RELEASE 1.44.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1194]
## Changelog

New features:
- Update elasticpress to 2.4 #1175 
- "Do you really want to leave this page without updating" alert #1191 
- Payments: add gform_stripe_get_plan filter #1202 (Hotfix)

Bugfixes:
- Proud Search Plus: Documents not indexing #1196
- Kiosk: external_link_prefix not set #1197 (Hotfix)
- Kiosk: Can't direct link to a directory entry (#1186)

Hotfixes since previous release
- Hotfix 1.43.1: Kiosk: external_link_prefix not set #1197 (wp-proud-actions-app) Nov 17 2017
- Hotfix 1.43.2:  Increase session lifetime to 14 days #1168 (wp-proud-core, wp-proudcity) Nov 19 2017
- Hotfix 1.43.3: Payments: add gform_stripe_get_plan filter #1203 (wp-proud-core, gravityforms) Nov 24 2017
- Hotfix 1.43.4: Payments: add gform_stripe_get_plan filter #1203 (wp-proud-core, gravityforms) Nov 24 2017
- Hotfix 1.43.5: WordPress Core 4.9.1 security update Nov 29 2017

WordPress Core Update 
- The WordPress Core security and maintenance release 4.9.1 (https://wordpress.org/news/2017/11/wordpress-4-9-1-security-and-maintenance-release/) was annoced on November 29 2017.  We deployed it to all sites hosted on the ProudCity Platform on November 29 2017 as Hotfix 1.43.5

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/f55508cddea0880f2ed2e0e0d10bad3773b8ee3c)
- wp-stateless 2.1.0 -> 2.1.1
- duplicate-post 3.2 -> 3.2.1
- disable-comments 1.7 -> 1.7.1
- wp-mail-smtp 0.11.1 -> 0.11.2
- siteorigin-panels 2.5.14 -> 2.5.16
- so-widgets-bundle 1.11.0 -> 1.11.2
- wp-job-manager 1.29.0 -> 1.29.1
- elasticpress 2.3.2 -> 2.4

### Scripted updates
```
# @todo: do we want to run this?
# Change all /wp-content/uploads/ references to GCE
wp search-replace $(wp option get siteurl --allow-root)/wp-content/uploads/ https://storage.googleapis.com/proudcity/${STATELESS_MEDIA_DIRECTORY} --allow-root
```
### Manual updates
- Get SR back on service-center `master`

### Testing emphasis
- [x] login from my.proudcity.com
- [x] login redirect
- [x] Responsive imgs
- [x] Login
- [x] Gravityforms
- [x] Search
- [x] Look at SR images
- [x] Auth0 #1139
- [x] Follow up #1170 office viewer

**Comment by jlyon** [comment]
pushed, posted, sent @kevindherman @lukefretwell @aschmoe
