### ISSUE TITLE
[meta] Adopting Gutenberg

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#1462]
- [ ] make pc blocks (content lists, headers, etc) compatible w gutenberg
- [ ] what do we do about SO Page Builder? https://siteorigin.com/gutenberg-compatibility-page-builder/. Relevant: https://siteorigin.com/thread/wordpress-5-0-page-builder-gutenberg-migration/
- [ ] move some custom metafields above Gutenberg?
- [ ] related issues with wp-seo (probably pc custom code?) https://yoast.com/yoast-seo-in-wordpress-5-0/#yoast-seo
