### ISSUE TITLE
Update PHP renderers in the Service Center for GA4

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2287]
**Source**
CM

Make sure we change the GTM tracking code per client.

WordPress holds the GTM and GA4 tracking identifiers in the `googlesitekit_analytics-4_settings` entry in `wp_options`. It's formatted as below.

```json
{
  "ownerID": 1,
  "propertyID": "<propertyID>",
  "webDataStreamID": "<streamid>",
  "measurementID": "<measurementid>",
  "useSnippet": true,
  "googleTagID": "<demo-tag-id>",
  "googleTagAccountID": "<accountid>",
  "googleTagContainerID": "<containerid>",
  "googleTagLastSyncedAtMs": 1686774110530
}
```

The value we're looking for is the `googleTagID` value to be inserted into the GTM code.

It looks like we could add our own REST route for it, though as the [StackOverflow comment says](https://stackoverflow.com/questions/64328214/headless-wordpress-is-there-a-way-to-access-data-in-wp-options-table-as-rest-en) it creates possible security issues. We'd want to whitelist the IP that is allowed to make the call, and the value that it's allowed to call to only the above entry in the `wp_options` table...or come up with some other method to make sure that we have security on our REST calls to the `wp_options` table.

These are `iframes` used specifically for kiosk applications and facebook. The two revelant lines are found here:

- https://github.com/proudcity/wp-proud-actions-app/blob/77ea3c2b88db3fa70e2e7cb1d6fdb1f78bf03ff0/templates/app.php#L31
- https://github.com/proudcity/wp-proud-actions-app/blob/master/wp-proud-actions-app.php#L284

The need to be updated to pull the GA4 key from the new option location and in the case of [`app.php`](https://github.com/proudcity/wp-proud-actions-app/blob/master/templates/app.php#L31) we need to make sure that we're creating the `ga` tracking code in the proper GA 4 format.

[Relevant Slack conversation](https://proudcity.slack.com/archives/C0AH683JQ/p1687455397189199?thread_ts=1687452672.615989&cid=C0AH683JQ).

**Tasks**
- [ ] add deprecation notice to Service Center facebook : https://www.lucastexas.us/wp-admin/admin.php?page=service-center-facebook
- [ ] add deprecation notice to Service Center kiosk: https://www.lucastexas.us/wp-admin/admin.php?page=service-center-kiosk

> With the update to Google Analytics 4 we are no longer able to track analytics for the Kiosk.

**Check GA4 on these sites**
Make sure that we aren't outputting 2 codes and do have our GA 4 single produced code

- [ ] look at GA 4 properties under the `analytics` user and add cities
