### ISSUE TITLE
WordPress 6.3 and jQuery 3.7.0

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2301]
**Source**
CM

WordPress 6.3 will update the version of [jQuery to 3.7.0](https://core.trac.wordpress.org/ticket/58083). There are some possible breaking changes that we need to be aware of and check when we make this update.

Biggest issue is that they are changing the selector engine. They are also changing IE support, but WP doesn't really support IE anymore.

[6.3 Release date is early August](https://make.wordpress.org/core/6-3/).

**Tasks**

- [ ] check jQuery compat with our version of Bootstrap
- [ ] check all JS related site functions
- [ ] review other changes in [6.3](https://make.wordpress.org/core/2023/07/18/wordpress-6-3-field-guide/)
