### ISSUE TITLE
hard code admin menu order

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2315]
**Source**
CM

Hard code menu order and remove the WP Admin Menu plugin. This will stop users from being able to change the menu and mean we don't have random things happening to the menu that confuse users like we did in #2302 

See Google Docs for order: https://docs.google.com/document/d/1aBc2KgkrmumzhnoZKMS5dcmSCXA0JmJy8c2pSSAG4Ng/edit#heading=h.vev1j0lpocak

## Tasks
- [x] "admin" level items like Plugins should be on there own and have a PC standard blue background with white text so that they are obviously "admin" stuff 
- [x] what do we do about the `Appearance` and `WP Dashbord` menu items that show for editors but we don't want them to have?

## Launch

- [x] add release file
  - activate new plugin
  - deactivate old plugin Admin Menu Editor
  - delete `ws_menu_editor` from `wp_options` 

## Plugins Edited/Update

- [x] `wp-proud-admin`
  - stripped out the admin menu styles to move them to `wp-proud-admin-menu` plugin
  - `proudcity-patterns` is really where these styles lived and that was updated
- [x] `wp-proud-admin-menu`
  - added to control the layout and styles of the admin menu  

## Testing items

- [x] media folder formatting in the media library was weird. It has a different layout than the standard content types so it needs some additional consideration: https://beta.proudcity.com/wp-admin/upload.php
![Screen Shot 2023-09-07 at 3 44 37 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/9140d6e0-0a75-4858-9a89-c40982770d29)

- [ ] logged in as support@ tools links to page not found: https://beta.proudcity.com/wp-admin/pc_tools (screenshot below) Sub items of tools works fine (broken links and redirects). 
![Screen Shot 2023-09-14 at 3 38 16 PM](https://github.com/proudcity/wp-proudcity/assets/6032426/1c517f9d-7efc-4966-af7e-1c226b27d639)

**Comment by lukefretwell** [comment]
@curtismchale see comments re: color: https://github.com/proudcity/wp-proudcity/issues/2328

**Comment by lukefretwell** [comment]
@curtismchale I think a spacer here would be great. As far as the coloring, my suggestion would be to just change the background color, using something subtle like #adcdff or #a1d3ff from USWDS (https://designsystem.digital.gov/design-tokens/color/system-tokens/#blue).

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman feedback:

* re: coloring see: https://github.com/proudcity/wp-proudcity/issues/2315#issuecomment-1692306467
* I'd prefer the original icons since we've use those in the help and want them to match
* When clicking 'Menu' get this message: "Your theme does not support navigation menus or widgets."
* 'Menu' should be 'Menus'
* 'Staff Listing' should be 'Contacts'
* 'Job Listings' should be 'Jobs'
* Shouldn't 'Mail Optin' be higher with PC admin access?
* Isn't customize available to all? That's what's indicated in the doc.
* Isn't tools available to all? That's what's indicated in the doc.
* Auth0 location above SMTP in WP admins menu

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman One issue we need to address is our Tools menu (not the one currently with the blue background). Currently when you go there it doesn't go anywhere because there is no content.

I could send it to any of the sub-items, but some sites don't have WP Rocket and we have a longer term plan to remove the Broken Link Checker plugin. That means we should likely send them to the Redirects menu item by default...or put some content on the first tools page that describes what it's all about.

There is a new version of the plugin on Beta. I did **not** address everything @lukefretwell mentioned, but I got the highlights. Regarding colour, remember our users never see the blue part.

**My Notes**
See this for changing the sub-menu item so it doesn't match the Menu item: https://wordpress.stackexchange.com/questions/206471/how-to-only-add-a-top-level-admin-menu-without-it-creating-a-sub-level-menu

**Comment by curtismchale** [comment]
@lukefretwell on the icons, So you want me to change out every icon with our custom ones even the WP default ones? I thought we wanted to get back to standard WordPress as much as possible?

**Comment by lukefretwell** [comment]
@curtismchale for now staying with Font Awesome icons would be ideal. I'd like to just focus on the menu order/labels and make sure it's all functional, then review/discuss iconography changes.

**Comment by curtismchale** [comment]
@lukefretwell Beta now has a version with icons updated to Font Awesome.

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell in the testing checklist in the issue description I checked off the media library formatting issue that appears resolved and added a new item for tools when logged in as support@.

**Comment by lukefretwell** [comment]
@curtismchale my suggestion would be to nix to the border on the admin menu.

**Comment by lukefretwell** [comment]
Feedback:

- [ ] On click is funky, icon/text move to the left and the icon turns white.
- [ ] Under 'Contacts', 'All Staff Members' should say 'All Contacts'.
- [ ] When clicking one of the submenus, the menu above it turns the text white.

**Comment by lukefretwell** [comment]
@curtismchale just flagging the above checklist
