### ISSUE TITLE
Update Stripe Webhook API Endpoints

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2339]
**Source**
CM

https://dashboard.stripe.com/webhooks

We can only run a few different versions of the API at a time. Currently this means we can't use the latest version as there are other webhook endpoints with differing versions. We need to update all the webhook endpoints to the latest version.

**Tasks**
- [ ] get list of sites
- for each site
- [ ] update webhook to latest API
- [ ] add new signing secret and test secrets to the Gravity Forms setup
