### ISSUE TITLE
Add GTranslate to fix Google translate form fields missing labels error

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2371]
## Source

* https://github.com/proudcity/wp-proudcity/issues/2354

## Describe the bug
The feedback form on Google Translate is missing form labels. Can we change how we embed the form so that it's accessible to users and has labels?

![CleanShot 2023-09-20 at 06 42 38](https://github.com/proudcity/wp-proudcity/assets/74561/db0cf9ea-823e-4607-9c27-a17cc7fff17c)

This translate form comes from including the widget at `wp-proud-core/modules/proud-widget/widgets/google-translate/google-translate-widget.class.php` though we don't include the feedback form, this gets brougt along with the translate code we add.

## Possible fixes

1. Look at the [GTranslate plugin](https://wordpress.org/plugins/gtranslate/). This is a change to the styles we currently have and I'm not sure it can be styled to fit with what we currently have. According to [this forum thread](https://wordpress.org/support/topic/accessibility-issue-with-google-translate-form/) the form is accessible now.

I could probably do some "hackery" to get their widget to show only after you click the icon we currently have.

2. Add our own integration with the [Google Translate API](https://cloud.google.com/translate). This will cost us something.

Ideally we'd build a custom plugin to handle our translation needs with the [PHP API](https://cloud.google.com/php/docs/reference/cloud-translate/latest).

**2023-09-20**

`1016` - seems we're using an [old version of the translate](https://groups.google.com/g/google-translate-api/c/gQckdv3AyP4?pli=1) functions that isn't accessible so we need to update.

**2023.09.27**
- [x] verify this works as expected on petaluma theme
- [x] verify this works as expected on SR theme
- [x] add gtranslate to composer file
- [x] activate gtranslate in release build file
- [x] setup plugin activation in release build file
- [x] push settings for plugin to all sites in release build file

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
Use GTranslate with a shortcode in place of the current Google Translate. This replaces the current google translate item.

**Tasks**
- [ ] check service center settings page for options and how they impact the new translate widget

**Comment by curtismchale** [comment]
@kevindherman @lukefretwell this is up on Beta now. Since Beta uses the SR theme it doesn't look quite right but I'll be fixing that as well and checking Petaluma.

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman can we use the settings I configured in beta to be platform wide? Given that some of the settings don't gel with our CSS, I'd like to keep the configuration hidden for now.

**Comment by kevindherman** [comment]
Translate options test list:

- [ ] SR https://beta.proudcity.com/
- [ ] Standard in top nav https://www.cityofmontclair.org/
- [ ] Recovers theme, top bar with label https://publicworks.marincounty.org/
- [ ] Centered theme, top bar with label https://cityofpetaluma.org/
- [ ] Consider with alert bar activated across these

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman notes:

- [ ] happens when changing to a different language than default, works when changing back to default
- [ ] this isn't an issue when navbar moves to bottom of page when screensize is smaller
- [ ] language dropdown is hidden when navbar is at the bottom (screenshot added)

![Screenshot 2023-09-28 at 10-27-11 San Rafael California - The City with a Mission](https://github.com/proudcity/wp-proudcity/assets/1569463/83fad544-7562-4ac8-abba-e33f6ab795b7)

**Comment by lukefretwell** [comment]
Languages:

- [ ] English
- [ ] Spanish
- [ ] French

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman I selected all languages.
