### ISSUE TITLE
Update WordPress - core, plugins 2023.10.05

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2391]
**Akismet** - 5.2 -> 5.3 

[Release notes](https://wordpress.org/plugins/akismet/#developers)

- Nothing that affects us
- @kevindherman do we even use this plugin?

**Gravity Forms** - 2.7.13 -> 2.7.15

[Release Notes](https://docs.gravityforms.com/gravityforms-change-log/)

- they changed the default form styles so we need to check to see if that changes anything for us
  - in theory this is for "new" sites only and since we start off a template all the time we don't really have a "new" site where GF is installed for the first time. 

**Gravity Forms Stripe** - 5.1.1 -> 5.2.0

[Release Notes](https://docs.gravityforms.com/stripe-change-log/#5-2-0-2023-09-20)

- just bug fixes nothing should affect us

**iframe** - 4.6 -> 4.7

[Release notes](https://wordpress.org/plugins/iframe/#developers)

- JavaScript clean up we should just check that it works as expected still but it should be fine

**SiteOrigin Panels** - 2.26.0 -> 2.26.1

[Release notes](https://wordpress.org/plugins/siteorigin-panels/#developers)

- bugfixes we should be fine

**Google Site Kit** - 1.109.0 -> 1.111.0

[Release notes](https://wordpress.org/plugins/siteorigin-panels/#developers)

- updates and bugfixes nothing looks like it should be an issue

**SO Widgets Bundle** - 1.55.0 -> 1.55.1

[Release notes](https://wordpress.org/plugins/so-widgets-bundle/#developers)

- minor bugfixes we should be fine

**WP Job Manager** - 1.41.0 -> 1.42.0

[Release notes](https://wordpress.org/plugins/wp-job-manager/#developers)
[SVN Log](https://plugins.trac.wordpress.org/log/wp-job-manager)

- release notes are blank actually so we looked through the SVN log
- the commits between 1.41.0 and 1.42.0 are all about icons and branding so it looks fine to me

**WP Media Folder** - 5.6.1 -> 5.6.4

[Release Notes](https://www.joomunited.com/changelog/wp-media-folder-changelog)

- nothing should affect us

**WordPress SEO** - 21.1 -> 21.3

[Release notes](https://wordpress.org/plugins/wordpress-seo/#developers)

- bugfixes we should have no issues

## Tasks

- [x] make sure GF new theme doesn't affect us
- [x] confirm that iFrame works as expected
- [x] confirm that WP Job Manager looks as intended
