### ISSUE TITLE
Block bots

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2419]
## Source
CM

## Describe the bug

We've been seeing huge traffic spikes from bots with names like `thesis-bot`, `fidget-spinner-bot`....which have coincided with downtime on the sites that see the traffic.

We need to add a way to block these bots by user agent string that can be deployed to all sites. Initially I think we can use [rewrite rules](https://serverfault.com/questions/802574/block-web-requests-based-on-a-portion-of-the-user-agent-string-not-working) to do this. I think we'd need to `cat` them into `entrypoint.sh`.

It would be nice if there was a way to do this without deploying a new build to each site, but at this point that's what I think we need to do.

**Tasks**
- [ ] test cat for rewrite rules to `entrypoint.sh`
- [ ] compile list of bot names (curtis has this in some daily update notes)
- [ ] roll this out to everyone

**or**
Add rules to the [VPC network](https://github.com/proudcity/wp-proudcity/issues/2419). That is global and instantly deployed.

**Bot Names to Block**
- `thesis-research-bot`
- `fidget-spinner-bot`

There are also some odd query params like this `?fbclid=IwAR35Gugl6k2UA7uvSBCzlCVa1HDI8s7ajx7XdgZGiWgjRzPyZoF-7iVfRf0`. After some research those appear to be a new [Facebook thing](https://www.glowmetrics.com/blog/what-is-fbclid-how-to-remove-fbclid-parameter-from-google-analytics/#gref) and thus are valid traffic.

## QA

Notes:

* 

Links:

*

**Comment by curtismchale** [comment]
In a current talk we would block all AI bots, SEO research bots, just bots in general (not Google search index and general search bots). We're paying for this service increase in server resources without passing it along.
