### ISSUE TITLE
META: Google Analytics Events

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#242]
With #241, I wanted to track all of our custom GA events:

`eventCategories`:
- [x] Score: Used to display the ProudScore in Calypso. More: #241
- [x] Heart: Tracks most hearted content: #240
- [x] Answer: Tracks when an answer is viewed
- [x] Submission: Tracks when a Gravity form is submitted- [ ]
- [x] SearchAutocomplete: Tracks when an autocomplete search is made (eventLabel=search term)
- [x] SearchClick: Tracks when an autocomplete result is clicked
- [ ] Payment: Tracks when a payment is made (via Gravity Forms)
- [ ] JobApply: Tracks when the Apply button is clicked on a Job Submission
- [ ] Issues: @todo: needs defn

The `eventAction` is always an Int, the `eventLabel` is always the full url to the post.

Calls should look like this:

```
$window.ga('send', {
  hitType: 'event',
  eventCategory: 'Score',
  eventLabel: node.title.rendered,
  eventAction: $rootScope.analyticsUrl,
  eventValue: node.hearted ? +5 : -5
});
```

**Comment by jlyon** [comment]
Make sure we're all set with Proudscore #241

**Comment by jlyon** [comment]
QAing + adding in stuff from #241 
- [ ] Score: Used to display the ProudScore in Calypso. More: #241
- [ ] Heart: Tracks most hearted content: #240
- [ ] Answer: Tracks when an answer is viewed
- [ ] Submission: Tracks when a Gravity form is submitted- [ ]
- [ ] SearchAutocomplete: Tracks when an autocomplete search is made (eventLabel=search term)
- [ ] SearchClick: Tracks when an autocomplete result is clicked
- [ ] Payment: Tracks when a payment is made (via Gravity Forms)
- [ ] JobApply: Tracks when the Apply button is clicked on a Job Submission
- [ ] Issues: @todo: needs defn
