### ISSUE TITLE
When a link name is repeated multiple times like "Add to Calendar", associate the link name with the title of the event

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2511]
## Build

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/4c60797e-c831-42b3-8f81-439c69a8fb3e?project=proudcity-1184)
- [master](https://console.cloud.google.com/cloud-build/builds;region=global/095b8cbb-dec2-4d8e-87d6-9f1d588905b4?project=proudcity-1184)

## Source

https://airtable.com/appRFUc45sF4yWFut/tbl51inE74gEWlB0x/viwG9G4vAjsjQEh4g/reczzFA8bveqA08Ge?blocks=hide

## Describe the bug

When a link name is repeated multiple times like "Add to Calendar", associate the link name with the title of the event so that a screen reader user is clear what they are adding to the calendar.

## Recommendations

Use aria-labelled by to associate the link to the Event title.  See reference: https://www.w3.org/WAI/GL/wiki/Using_aria-labelledby_for_link_purpose#:~:text=With%20the%20aria-labelledby%20attribute%2C%20authors%20can%20use%20a,purpose%20of%20the%20link%20unambiguous%20%28see%20example%201%29.

## Screenshots

![Add to Calendar](https://github.com/proudcity/wp-proudcity/assets/1569463/cb287b07-45e7-4164-8968-d581c8ee9d02)

## Tasks
- [x] upgrade [atcb](https://github.com/add2cal/add-to-calendar-button/releases/tag/v2.6.8) to latest version
- [x] revamp webpack theme build to move new scripts to `dist` folder
- [x] enqueue new `atcb` javascript library
- [x] confirm that it works as the old library and if not fix it
- [x] add the `aria label` as described above
- [ ] check our other themes for custom clients that need this rolled out

**Comment by curtismchale** [comment]
I'm not sure I even see the option to do this in `atcb` so I've [asked a question](https://github.com/add2cal/add-to-calendar-button/discussions/573) about how to accomplish the aria labels.

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman this is up on Beta now, [see the demo page](https://beta.proudcity.com/downtown-holiday-parking-program_-ck/).

Note, the styling is totally different and way more limited with the Add To Calendar Button (atcb) now. I did my best, but then modified the directions button to get it as close as I could. If you inspect the CSS you'll see that some of the values are wildly different to try and get it to look similar.

Luke, if you're going to try and mess with the CSS a bit the only values we have to work with in `atcb` are the ones with the `:host` prefix. We can't write custom CSS for it anymore.

If this looks okay, I need to check SR and Petaluma to make sure that their custom themes look as expected before this can be launched.

On the plus side, we are now on the latest `atcb` and will get the benefits of updates as we go.

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell the directions icon looks to be styled differently:
![Screen Shot 2024-03-21 at 9 58 08 AM](https://github.com/proudcity/wp-proudcity/assets/6032426/310bd87f-872c-4562-a23d-133a0102f92a)

Everything else seems good to me.

**Comment by curtismchale** [comment]
@kevindherman the ATCB button comes with it's own SVG file and I don't see a way to change it. We can use another [Font Awesome icon](https://add-to-calendar-button.com/configuration) that's **not** a Pro icon if you'd prefer. But we don't pay for Pro so I can't change the weight of the icon to better match the weight of the ATCB icon.

**Comment by kevindherman** [comment]
the ATCB button is fine with me @curtismchale but it doesn't match the "Directions" font size next to it. I just think they should match. So if the ATCB is predetermined the directions button should probably match up to ATCB. @lukefretwell what do you think?

**Comment by lukefretwell** [comment]
@curtismchale @kevindherman playing with the CSS, this seems to work. Not sure how to get them top-aligned.

.fa.fa-map-marker::before {
  content: "\f3c5";
  margin-right: .8rem;
}
font-size: 1em;
  padding: .3em 1em;
  font-family: Roboto,sans-serif;
}

Suggested icon:

<i class="fa-solid fa-map-pin"></i>

**Comment by curtismchale** [comment]
@lukefretwell @kevindherman revised version is up. If we're happy with it I can deploy it later today or tomorrow.

**Comment by kevindherman** [comment]
Definitely better @curtismchale. The height of the direction button still seems too big though.

That's my last comment on this, passing the baton to @lukefretwell.

**Comment by curtismchale** [comment]
![CleanShot 2024-03-21 at 13 31 19](https://github.com/proudcity/wp-proudcity/assets/74561/27cdfdca-9012-404a-83b7-401e4802b88f)

@kevindherman you can see how far off it is from alignment here, 1px or so.

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.03.26.1154
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2024.03.26.1154
