### ISSUE TITLE
Update meeting list using list view to match event list changes

### ISSUE THREAD

**Issue by kevindherman** [proudcity/wp-proudcity#2590]
## Builds

- [Staging](https://console.cloud.google.com/cloud-build/builds;region=global/ec9b4143-4d2c-4eeb-bd4c-8918828c4baf?project=proudcity-1184)
- [Prod](https://console.cloud.google.com/cloud-build/builds;region=global/aa2cbb21-892d-4f4e-85bb-6e78a124998b?project=proudcity-1184)

Includes: #2507 
Includes: #2586 

## Tasks
- [x] Edit ProudCity them
- [x] Edit SAN Rafael theme
- [x] edit Petaluma theme

## issue

Meeting list widget using the list view should match event list formatting from recent changes:

1. https://github.com/proudcity/wp-proudcity/issues/2496
2. https://github.com/proudcity/wp-proudcity/issues/2497

See Belvedere homepage to see how meetings and events now look different:
https://www.cityofbelvedere.org/

![Screenshot 2024-08-21 at 1 54 20 PM](https://github.com/user-attachments/assets/ca62b954-3791-4d24-803e-9a4ce1695797)

**Comment by kevindherman** [comment]
@lukefretwell @curtismchale I added this to the Pacific ADA milestone even though it's not direct feedback it's from their analysis.

**Comment by kevindherman** [comment]
@curtismchale @lukefretwell realized this may be a duplicate of this issue: https://github.com/proudcity/wp-proudcity/issues/2522

If yes, @curtismchale can you consolidate to what's most clear for you?

**Comment by kevindherman** [comment]
@curtismchale looks good on beta.
