### ISSUE TITLE
WP Stateless Gravity Forms addon

### ISSUE THREAD

**Issue by curtismchale** [proudcity/wp-proudcity#2612]
## Build

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/c11e41b7-a211-4e77-b7e7-78429a9b681c?inv=1&invt=AbmY5Q&project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/9e5d3b25-7871-43c9-8584-2b92f9a1ecaf?inv=1&invt=AbmY5Q&project=proudcity-1184)

## Notes

WP Stateless [now has a Gravity Forms integration](https://wordpress.org/plugins/wp-stateless-gravity-forms-addon/#description). We currently run our own integration so we should evaluate this and drop our own code in favour of his package that they'll maintain.

Upgrading with #2611 to the latest Stateless stopped our current GF integration from working so we need to figure out why and how to fix it or move over to this integration.

## Tasks

- [x] does the WP Stateless GF addon just work - **YES**
  - [x] does it cause issues with older files not downloading? **NO** 
- [ ] there is a [GF Signature addon](https://wordpress.org/plugins/wp-stateless-gravity-forms-signature-addon/) as well we need to check
- [x] [check this line](https://github.com/proudcity/wp-proud-core/blob/2f2234314b4c1d7108e8365d23f35278b7c0e33c/plugin_override/gravityforms/proud-gravityforms.php#L36) as it gives errors under PHP 8.3. Likely need to add a check to make sure the `class_exists` and that the call to `get_module` returns the expected array. Only then `try` .

**Comment by curtismchale** [comment]
@kevindherman There is a GF Signature addon for WP Stateless as well. We have the plugin installed but not active in the default build. Do you know which customers use this plugin so I can test it?

**Comment by kevindherman** [comment]
@curtismchale I don't think anyone is actually using it. We've pushed people to just use the consent field.

**Comment by curtismchale** [comment]
Deployed

Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2025.01.09.0557
Builds: https://github.com/proudcity/proud-recipes/releases/tag/2025.01.09.0557
