### ISSUE TITLE
Add dashboard widget (Year-end checklist)

### ISSUE THREAD

**Issue by lukefretwell** [proudcity/wp-proudcity#2617]
## Builds
Includes #2621 

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/9a4b98c9-361e-4b53-af29-ab1db55b9aad?project=proudcity-1184)
- [prod](https://console.cloud.google.com/cloud-build/builds;region=global/28692d86-02c4-43bd-9278-6cedc7b1367d?project=proudcity-1184)

## Task
- [ ] Title: Year-end checklist
- [ ] Description (6 words min.): Start cleaning, get housekeeping.
- [ ] Icon ([reference](https://fontawesome.com/search?o=r&m=free): `<i class="fa-solid fa-spray-can-sparkles"></i>`
- [ ] Color ([reference](https://designsystem.digital.gov/design-tokens/color/system-tokens/)): #c84281
- [ ] Button text: Year-end checklist
- [ ] Button link: https://help.proudcity.com/end-of-year-local-government-website-clean-up-checklist/
- [ ] Location: Top left

**Comment by lukefretwell** [comment]
Feedback:
* Sorry, meant below news item top left
* This icon is probably better since we changed the context elsewhere: https://fontawesome.com/icons/calendar-check?f=classic&s=regular
* Note the color: #c84281

@curtismchale @kevindherman

**Comment by kevindherman** [comment]
@lukefretwell thank you for clarifying.

**Comment by curtismchale** [comment]
Deployed

Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.10.30.1608
Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.10.30.1608

**Comment by curtismchale** [comment]
Need to redeploy to fix the order. Does **not** include any further work on #2621 as that notice was removed late yesterday once the information was collected.

## Builds

- [staging](https://console.cloud.google.com/cloud-build/builds;region=global/c7a91efe-8b1a-43f4-92c9-406579d69bc3?project=proudcity-1184)

**Comment by curtismchale** [comment]
Fixed order deployed

Build: https://github.com/proudcity/proud-recipes/releases/tag/2024.10.31.0627
Composer: https://github.com/proudcity/wp-proudcity/releases/tag/2024.10.31.0627
