### ISSUE TITLE
Release 1.15.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#496]
### Changelog

Bugfixes
* Feedback form page break formatting #477 
* Documents: File Remove button does nothing #263 
* "Agency" should be "Department" in Agency, Contact table headers #513 
* Fix admin sidebar icon styling #522 
* Add link styling bad so you can't autocomplete #515 

Updates and new features
* Improve Menu Quickedit interface #12
* 311 Actions app: Allow embedded iframe, external link #509 
* New widget: Embed a document from the document library #502 
* Allow non-email addresses for Agency contact field #514
* Agency, Contact lists: Allow Social, Agency columns to be hidden #511 .
* Submenu widget: Allow pill style #512 
* Display contact info on map with wp-proud-locations #519 
* Show location featured media in map #382 

Hotfixes since previous release
* 1.14.1 issues with SR: Header: random image #482 (wp-proud-core)

WordPress Core Update 
* 

3rd party plugin updates ()
* auth0 3.2.5 -> 3.2.6
*google-analytics-dashboard-for-wp 4.9.3.1 -> 4.9.3.2 https://wordpress.org/plugins/google-analytics-dashboard-for-wp/changelog/
* edit-flow  0.8.1 -> 0.8.2 https://wordpress.org/plugins/edit-flow/changelog/
* so-widgets-bundle 1.6.5 -> 1.7.1  https://wordpress.org/plugins/so-widgets-bundle/changelog/

### Scripted updates
```
wp option set 'wp_quick_menu_format' select --allow-root
```

### Manual updates
- [ ] 

### Testing emphasis
- [x] SR Set up SR issues #309
- [x] SR custom theme
- [x] Login
- [x] SR Gravityflow enabled on WC, perms working, perm plugin disabled
- [ ] WA national weather service app working on @todo
- [x] Are previous hotfixes still applied ? #267
- [x] Gravityforms
- [x] Search
- [ ] Proudpack integration, permissions
- [ ] New random image hero unit option #483 @todo still broken

**Comment by jlyon** [comment]
Pushed release, posted blog post, sent mailchimp. @kevindherman @lukefretwell @aschmoe
