### ISSUE TITLE
Contact page changes

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#507]
- [x] Make contact form default tab #512 
- [x] Rm Agency col #511
- [x] Change "Agency" to Department #513

**Comment by kevindherman** [comment]
@jlyon how are contacts ordered on the elected officials list and the city staff list?

**Comment by kevindherman** [comment]
@jlyon on the staff contacts view, contacts are added to that list by selecting the "City Staff" category.  If you add a specific department category it shows the department and city staff pills, I did this for Rebecca's contact information as you can see below.  Is there a way to only show the department? 

https://san-rafael-ca.proudcity.com/people/?filter_categories%5B%5D=58
![screenshot 2016-09-15 10 20 23](https://cloud.githubusercontent.com/assets/6032426/18553466/849d9c50-7b2e-11e6-89a5-e8eb7ab4bb18.png)
![screenshot 2016-09-15 10 20 40](https://cloud.githubusercontent.com/assets/6032426/18553465/849b66d8-7b2e-11e6-884f-80746c3474d3.png)

**Comment by jlyon** [comment]
This is now possible with the new setup.  Basically we should 

1. Set up new depts for each department. Tag everyone.
2. Edit the Contact list widget on https://san-rafael-ca.proudcity.com/wp-admin/post.php?post=5221&action=edit to display all departments except Elected officials.
3. Get rid of the staff contacts Department tag.

Does that make sense @kevindherman?

**Comment by jlyon** [comment]
Re: ordering: it currently just orders by the post date, I believe. I created new issue to dig into this deeper #523.
