### ISSUE TITLE
RELEASE 1.16.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#528]
### Changelog

Bugfixes
* Slider menu starting level 1 not height checked #601
* Search: departments have "sorry, this menu has been initialized without a valid option" message in search results #594
* Phone number missing from location detail #592 
* 311 actions box: Increase limit to number of Issue categories displayed, number of posts within a category that are shown #595
* Social media links appearing in Agency table even when Hide checkbox is checked #588
* Document list table giving fatal error #584
* Add new location error #585
* Form Issue not showing in 311 app #571
* & symbol displaying as HTML code on issue topics #563
* External link departments not linking out for new image display style #569 
* Social wall breaks to 2 columns on firefox #558
* Gap on sliding menu #557
* Location detail shows email icon even if email detail isn't included #590

Updates
* Allow ordering documents, contacts, agencies #521 
* Agency: Add ability to turn contact name into link #593 
* Topnav style: add border if topnav color is white #599
* Map: Add parking icon #591
* Fix issue display in search #559
* Forms: add surveys #500 (Contact us to enable)
* Add card display for docs #577 
* Add Broken link checker #570
* Content lists: Limit display options to only what is possible for post type #568
* Add Category setting to Events list panel #573
* Posts list: 0 should show all items, cutting off at 10 #565
* Answers: Create content list widget #488
* Agency: Add "Do not display in lists" option #499
* Documents list: add Mini List display #589
* Agency list: Add new media teaser type #553
* Add transparent navbar option #554
* Add featured post option for news + events #555
* Allow icon additional icon sets for iconpicker #556
* 311 actions app: Add custom tab #530
* 311 actions app: Don't show tabs if only one tab is enabled #551

Hotfixes since previous release
* 1.15.1: Sep 22 2016: Primary Links submenus are displaying documents instead of the menu #534 (wp-proud-core)
* 1.15.2: Sep 22 2016: documents pager broken #506 (wp-proud-core)
* 1.15.3: Sep 23 2016: Documents: unable to edit the published info, the area to edit won't expand #544(wp-proud-document)
* 1.15.4: Sep 23 2016: Email, telephone links  open blank tab #537 (wp-proud-theme)
* 1.15.5: Sep 23 2016: Adding location: fields not set properly in Address autocomplete #527 (wp-proud-document)
* 1.15.5: Sep 28 2016: Agency: Add "Do not display in lists" option #499 (wp-proud-core, wp-proud-agency)
* 1.15.7: Answers: Create content list #466 (wp-proud-core, wp-proud-theme)
* 1.15.8: #488, #500, #553, #554, #555, #556, #558, #559, #561, #563, #569, #570, #571, #573, #577  (wp-proud-core, wp-proud-admin, wp-proud-search, wp-proud-actions-app, wp-proud-theme)

WordPress Core Update 
* There is no WordPress core update in this release.

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/340459819ce83baa164b82dc78dd5a33b8bc250c)
* siteorigin-panels 2.4.15 -> 2.4.16 https://wordpress.org/plugins/siteorigin-panels/changelog/
* w3-total-cache 0.9.4.1 -> 0.9.5.1 https://wordpress.org/plugins/w3-total-cache/changelog/
* auth0 3.2.6 -> 3.2.9 https://wordpress.org/plugins/auth0/changelog/
* rest-api 2.0-beta13 -> 2.0-beta14 https://wordpress.org/plugins/rest-api/changelog/
* wp-api-menus 1.3.0 -> 1.3.1 https://wordpress.org/plugins/wp-api-menus/changelog/
* wordpress-seo 3.5 -> 3.6.1 https://wordpress.org/plugins/wordpress-seo/changelog/

### Scripted updates
```
 wp search-replace 'govenment' 'government' --allow-root
# Already added link checker stuff
```

### Manual updates
- [ ] 

### Testing emphasis
- [ ] page builder update
- [x] SR: park icons showing up for some parking locations #591 #592
- [x] Email icon in map details #590
- [ ] Search: departments have "sorry, this menu has been initialized without a valid option" message in search results #594 
- [x] Admin menus (check Site link, does link Checker appear?)
- [x] Autocomplete works when adding locations
- [x] Vote app
- [x] SeeClickFix integration
- [x] SR custom theme
- [x] Login
- [x] SR Gravityflow enabled on WC, perms working, perm plugin disabled
- [ ] WA national weather service app working on
- [x] Are previous hotfixes still applied ? #267
- [x] Gravityforms
- [x] Search
- [x] Proudpack integration, permissions
- [x] New random image hero unit option #483

**Comment by jlyon** [comment]
Pushed release.  Added release to GH.  Need to add blog post and send mailchimp later tonight.  Will post back here when that's done @kevindherman @lukefretwell @aschmoe

**Comment by jlyon** [comment]
Sent out the email and posted the blog post last night @kevindherman @lukefretwell @aschmoe
