### ISSUE TITLE
RELEASE 1.21.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#698]
### Changelog

Updates and new features
- Service Center: Local Services tab #616
- Html hierarchical sitemap page #730
- Events: share #720
- Infrastructure: Upgrade to php7 #727 
- Infrastructure: Upgrade Auth0 to latest version platform-wide #726 
- Allow default page service center settings to be set #699 

Bugfixes
- Login/redirect issue #723 
- Service center: path has two slashes after the tld #738 
- Service Center Standalone: Add favicon #717
- Documents list: padding between tags #735 
- Alert bar hidden beneath nav #706 

Hotfixes since previous release
- 1.20.3: Dec 2 2016: SR: allow default page service center settings to be set #699 (wp-proud-actions-app, wp-proud-admin)
- 1.20.4: Dec 6 2016: SR: Service Center backend settings #616 (wp-proud-actions-app, wp-proud-admin, wp-proud-location, wp-proud-core)
- 1.20.5: Dec 8 2016: SR: San Rafael Service Center updates #616 (wp-proud-core, wp-proud-actions-app, wp-proud-admin)
- 1.20.6: Dec 8 2016: SR: Release launch (wp-proud-search, wp-proud-elastic, wp-proud-core)
- 1.20.7: Dec 13 2016: SR: Elastic Search multisite integration (wp-proud-search, wp-proud-search-elastic)
- 1.20.8: Dec 13 2016: Update to hours (wp-proud-actions-app, wp-proud-core)
- 1.20.9: Dec 13 2016: Issues with Dashboard link logging you out (wp-proud-admin), Service Center: Hours: Additional options #729 (wp-proud-actions-app) 
- 1.20.10: Dec 13 2016: Streamlining SMTP, wp-stateless configuration #597 (wp-proudcity, wp-stateless) 

WordPress Core Update 
- There is no WordPress core update in this release. The newly-release WordPress Core 4.7 Feature Release will be pushed to the Platform as a hotfix on December 15, 2016.

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/)
- wordpress-seo 3.9 -> 4.0
- siteorigin-panels 2.4.19 -> 2.4.20

### Scripted updates

```

```
### Manual updates
- [ ] Move SR over to stable Service Center branch
- [ ] Resync Auth0 settings

### Testing emphasis
- [ ] PHP7  #727
- [ ] Responsive imgs
- [x] img captions #486
- [ ] Login
- [ ] WA national weather service app working on
- [ ] Are previous hotfixes still applied ? #267
- [x] Gravityforms
- [ ] Search
- [ ] Logo upload (imagemagick) #737
- [ ] Service Center Standalone: Add favicon #717
- [ ] Email sending

**Comment by jlyon** [comment]
Pushed to platform, posted and sent mailchimp @kevindherman @lukefretwell @aschmoe .
