### ISSUE TITLE
RELEASE 1.22.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#747]
### Changelog

Updates and new features
- Downloads list/content page: Hide Download button if no file has been added #746 

Bugfixes
- Payments tab appearing when it should not #766 
- Form email notifications #764
- Update FontAwesome to 4.7 #760
- SMTP: Fix port for Google Cloud #751 

Hotfixes since previous release
- 1.21.1: Dec 15 2016: Resort drag and drop documents by published date (wp-proud-document) #693
- 1.21.2: Dec 16 2016: Fixing Document Display, backend (wp-proud-document, wp-proud-theme) #746
- 1.21.3: SMTP: Fix port for Google Cloud (wp-proudcity wp-config.php file) #751
- 1.21.4:  Show document preview even if document doesn't have a filesize  (wp-proud-theme) #753
- 1.21.5:  External link department not saving  (wp-proud-agency) #755
- 1.21.6: SR: event timezone (wp-proud-core) #741
- 1.21.7: De Leon: can't delete lorem ipsum (wp-proud-theme) #757
- 1.21.8: Update fontawesome to 4.7.0  (wp-proud-core, wp-proud-theme) #760
- 1.21.9:  Fixing call for service center settings (wp-proud-actions-app) #766
- 1.21.10:  Updating rest call to be aligned with new 4.7 core rest (wp-proud-actions-app, wp-proud-agency, wp-proud-document, wp-proud-issue, wp-proud-location, wp-proud-payment) #739

WordPress Core Update 
- The WordPress Core 4.7 update is included in this release.  There are few user-facing updates that our clients should notice. [View the full WordPress 4.7 release notes](https://wordpress.org/news/2016/12/vaughan/).

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/df2c4801a643a53a897dc921bb614e5e530571e2)
- google-analytics-dashboard-for-wp 4.9.4 -> 4.9.5
- wordpress-seo 4.0 -> 4.0.2
- say-what 1.8.0 -> 1.8.1
- wp-mail-smtp 0.9.5 -> 0.10.1
- siteorigin-panels 2.4.20 -> 2.4.21

### Scripted updates

```
wp plugin uninstall --deactivate rest-api --allow-root
wp plugin install rest-filter --allow-root

```
### Manual updates
- [ ] Move SR over to stable Service Center branch
- [ ] Resync Auth0 settings

### Testing emphasis
- [ ] PHP7  #727
- [ ] Responsive imgs
- [x] img captions #486
- [ ] Login
- [ ] WA national weather service app working on
- [ ] Are previous hotfixes still applied ? #267
- [x] Gravityforms
- [ ] Search
- [ ] Logo upload (imagemagick) #737
- [ ] Service Center Standalone: Add favicon #717
- [ ] Email sending

**Comment by jlyon** [comment]
@lukefretwell @kevindherman @aschmoe Pushed, posted, sent.
