### ISSUE TITLE
RELEASE 1.24.0

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#801]
### Changelog

Updates and new features
- Cleanup: Remove google-analytics-dashboard-for-wp from codebase #830 
-  Add title field to agency contact widget #794 
- Service Center: Make Custom Tab a post type #825 #805 
- Add Custom text area option to Issues post type #811 
- New approach to the social links display (Footer) #520 
- Fully move search autocomplete into service center #819 
- Icon Button Cards: break into two columns on mobile #605
- Service center: add loading icons #817 
- Service Center: make gforms auto-size height #817 
- Site origin: allow widget spacing and options #824 
- Add ability to select specific agencies in agency list widget #736

Bugfixes
- GForm next button send google analytics event as submit #826 
- Gform validation msg (error) has poor padding #828 
- Social wall not displaying all accounts' posts #368 #678
- Service Center: Facebook Mobile button #787 #680
- FIx padding with events create event button #630 
- Issue with /application-payment getting redirected #820 
- Teasers: setting to show: 0 doesn't work #818 
- Fix icon filter for fa fields in metabox #821 
- Change "agencies" to "departments" throughout #793
- CSS Gravityforms date picker, time field #750 

Hotfixes since previous release
- 1.23.1 Service Center: CSS tweaks (wp-proud-theme, wp-proud-actions-app) #653
- 1.23.2 Add ability to select specific agencies in agency list widget (wp-proud-core) #736

WordPress Core Update 
- The WordPress Core 4.7.2 security release is included in this release.  This release fixed three security issues in WordPress core.  [Read more](https://wordpress.org/news/2017/01/wordpress-4-7-2-security-release/).

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/b5cfe0272be98c555eedc2c02938297b4595bde6)
- wordpress-seo 4.1 -> 4.2
- say-what 1.8.2 -> 1.9.0
- siteorigin-panels 2.4.21 -> 2.4.23
- so-widgets-bundle 1.7.2 -> 1.8

### Scripted updates

```
# Change Agency to Department #793
echo "INSERT INTO wp_say_what_strings (orig_string, domain, replacement_string, context) VALUES ('Agency contact info','wp-agency','Department contact info',''),('Agency hours','wp-agency','Department hours',''),('Agency menu','wp-agency','Department menu',''),('Agency social media','wp-agency','Department social media',''),('View Agency','wp-agency','View Department',''),('Search agency','wp-agency','Search departments','');" | wp db cli --allow-root
```
### Manual updates
- [ ] Move SR over to stable Service Center branch
- [ ] Resync Auth0 settings

### Testing emphasis
- [ ] Responsive imgs
- [ ] Login
- [ ] Are previous hotfixes still applied ? #267
- [ ] Gravityforms
- [ ] Search
- [ ] Email sending
- [ ] Change Agency to Department #793 in widgets
- [ ] Update and test Custom tabs #825

**Comment by jlyon** [comment]
Pushed, posted sent @lukefretwell @kevindherman .


@aschmoe I merged in your actions-app branch and re-did the 1.24.0 tag on that plugin. Everything looked good to me.
