### ISSUE TITLE
[meta] Launch ProudCity Dashboad

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#810]
Start page
- [ ] Fix login redirect from /start
- [ ] City checklist takes too long to load -- loading icons?
- [ ] Scroll from slide 1 to 2 can be wonky - also check city with no stats (somewhere really random)
- [ ] Checklists are wonky, don't display html code, don't show videos
- [ ] Mobile
- [ ] Photo attributions

City api
- [x] Save static map image
- [x] save google places image
- [x] Save website thumb

Dashboard
- [ ] Login branding
- [ ] Login ?destination redirect  
- [ ] Checklist PATCH
- [ ] User: save EDIT
- [ ] User: DELETE
- [ ] User include link to permissions documentation
- [ ] Settings: Social Media accounts
- [ ] Settings: Payments finish up
- [ ] Settings: Analytics POST
- [ ] Integrations: Get list of currently enabled
- [ ] Integrations: Break into groups
- [ ] Analytics: Doesn't work in incognito (not using service account?)
- [ ] Deal w Roles, Perms
- [ ] DELETE site

Autosite
- [ ] force https
- [ ] Photo attributions

**Comment by jlyon** [comment]
Hotfix 1.32.3
