### ISSUE TITLE
RELEASE 1.25.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#832]
### Changelog

Updates and new features
- New Widget: contact info block #822 (hotfix)
- New Widget: Image/link collection #823 (hotfix)
- Change local services to "my services" #858
- Allow custom "Test" bar language #849
- Migrate feeds.proudcity.com #846
- Granicus integration #666
- Allow elasticsearch to serve content lists #866
- Look into spacing between sidebar and main #632

Bugfixes
- Fix FB tab #831 (hotfix)
- Agency contact info: tweaks #829 (hotfix)
- Department content displaying under left column #835 (hotfix)
- Change /service-center /app url to /mobile-app #837 (hotfix)
- Cannot upload json files in wp media upload #843 (hotfix)
- Fix url links in agency contact field #839
- Fix closing tag in Dockuments mini list block #862
- Service Center: Make date replace work with number values #855

Bugfixes
- 

Hotfixes since previous release
- 1.24.1 Missing div in agency contact info block #835 (wp-proud-agency) 
- 1.24.2 Adding Custom contact #822, Image button widgets #823; preparing for new ProudCity Dashboard (wp-proud-core, wp-proud-actions-app, wp-proud-agency, wp-proud-dashboard)
- 1.24.3  fixing remnants of  service center changes #837
- 1.24.4 Fixing fatal error with Adding Custom contact widget #822
- 1.24.5 Fixing fatal error with Adding Custom contact widget #822
- 1.24.6 Fixing fatal error with image set list widget #823
- 1.24.7 Cannot upload json files in wp media upload #843 (wp-proud-core)

WordPress Core Update 
- 

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/e5c7d021202def64a164d65348746511fe7477b1)
- duplicate-post 3.0.3 -> 3.1.2
- wordpress-seo 4.2 -> 4.3
- siteorigin-panels 2.4.23 -> 2.4.24
- so-widgets-bundle 1.7.2 -> 1.8.1

### Scripted updates

```

```
### Manual updates
- [x] Change feeds1 to feeds
- [x] switch feeds to live version
- [ ] K&KP: update proud_test_language #857
- [ ] rebuild elasticpress on SR and SRparks

### Testing emphasis
- [ ] Responsive imgs
- [ ] Login
- [ ] Are previous hotfixes still applied ? #267
- [ ] Gravityforms
- [ ] Search
- [ ] Email sending
- [ ] Change Agency to Department #793 in widgets
- [ ] Update and test Custom tabs #825

**Comment by jlyon** [comment]
pushed, posted and sent @lukefretwell @kevindherman @aschmoe
