### ISSUE TITLE
RELEASE 1.26.0

### ISSUE THREAD

**Issue by aschmoe** [proudcity/wp-proudcity#870]
### Changelog

Updates and new features
- Select event category when adding calendar widget #719 
- New tab option for Iconset links #880
- Disable Social, Departments by default on /contact page table #871
- Update auth0 #893 
- Service center tweaks #886 
- Image gallery mobile view formatting #704
- Constant Contact integration with forms #783

Bugfixes
- Document list widget title not showing #873 (hotfix)
- "Agency List" widget shows up as "Agency" even when switched to "Department" #868 
- Remove reported issues map layer on foursquare map if SeeClickFix is not used #883
- Facebook Service Center style tweaks #876
- Service Center Local: Date replacement formatting (MON should be Monday) #887 
- Agency list: Hiding Social doesn't hide column #885

Hotfixes since previous release
- 1.25.1 Danvers: department list widget not displaying selected dept's (wp-proud-core) #867
- 1.25.2 Search clicks on answers, payments in standalone app don't work (service-center) #869
- 1.25.3 PO: doc list widget title not showing (wp-proud-core) #873
- 1.25.4 esig: Theme esig page (wp-proud-core) #861

WordPress Core Update 
- 

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/3decfb27c120069ad8b036bd7af376c570f9cfa6)
- auth0: 3.2.14 -> 3.2.18
- wordpress-seo: 4.3 -> 4.4
- siteorigin-panels: 2.4.24 -> 2.4.25
- elasticpress: 2.1.2 -> 2.2

### Scripted updates

```
wp elasticpress deactivate-feature search
wp elasticpress deactivate-feature related_posts
```
### Testing emphasis
- [x] Responsive imgs
- [x] Login!!
- [x] Are previous hotfixes still applied ? #267
- [x] Gravityforms
- [x] Search
- [x] Email sending
- [x] K parks disable user role editor #783
- [x] K FB #876
- [x] WC service center MON issue
- [x] #883 K Reported issues on map
- [x] #868 K agency list

**Comment by jlyon** [comment]
Pushed, posted and send @aschmoe @kevindherman @lukefretwell
