### ISSUE TITLE
RELEASE 1.28.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#922]
### Changelog

Hotfixes since previous release
- 1.27.1 Disable Auth0 SSO #932 (wp-proudcity update script) 
- 1.27.2 Fixing typo #906 (wp-proud-core)
- 1.27.3 Kettering: Allow jobs taxonomy to be multi-slect #936 (wp-proud-core, wp-proud-theme)
- 1.27.4 Kettering: wrap text for long emails in contact block #934 (wp-proud-theme)

WordPress Core Update 
- There is no WordPress Core update in this release.

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/)
- intuitive-custom-post-order 3.0.7 -> 3.0.8
- wordpress-seo 4.4 -> 4.5
- elasticpress 2.2 -> 2.2.1

### Scripted updates
wp option update start_of_week 0 --allow-root

```

```
### Manual updates
- [ ] Enable w3tc on WC, K, KP, WCP
- [ ] Check that w3tc settings reset worked, dbcache is disabled

### Testing emphasis
- [ ] Redirects (sanrafaelfilm.com => https://www.cityofsanrafael.org/san-rafael-film/ should continue to redirect) #949
- [ ] www.proudcity.com -> proudcity.com #949
- [ ] .htaccess content
- [ ] login from my.proudcity.com
- [ ] login redirect
- [ ] Responsive imgs
- [ ] Login
- [ ] Are previous hotfixes still applied ? #267
- [ ] Gravityforms
- [ ] Search

**Comment by jlyon** [comment]
Pushed posted and sent @aschmoe @kevindherman @lukefretwell
