### ISSUE TITLE
RELEASE 1.29.0

### ISSUE THREAD

**Issue by jlyon** [proudcity/wp-proudcity#958]
### Changelog

New Features
- Make search box bigger, allow custom text to draw attention #943
- Change language for news, events and documents Dates to just "Posted [date]" #947
- Service Center: change "select answer type" to select question type #954
- Document embed in sidebar: make field description more informative #921

Bug Fixes
- Some media list view dept's showing as ovals #927
- Llong menus can't click "back" #948
- Wrap text for long emails in contact block #934
- Omit service_center_tab post type from search results #833
- Saving additional tracking code adds \ before quotes #960

Hotfixes since previous release
- There were no Hotfixes in this release cycle.

WordPress Core Update 
- There is no WordPress Core update in this release.

3rd party plugin updates (https://github.com/proudcity/wp-proudcity/commit/c8499b43722212712c9d92b490ecacbc23241f9c)
- duplicate-post 3.1.2 -> 3.2
- wordpress-seo 4.5 -> 4.6
- so-widgets-bundle 1.8.1 -> 1.8.2

### Scripted updates
```
wp option update start_of_week 0 --allow-root


```
### Manual updates
- [ ] Enable w3tc on WC, K, KP, WCP

- [ ] Check that w3tc settings reset worked, dbcache is disabled

### Testing emphasis
- [x] Redirects (sanrafaelfilm.com => https://www.cityofsanrafael.org/san-rafael-film/ should continue to redirect) #949
- [x] www.proudcity.com -> proudcity.com #949
- [x] .htaccess content
- [ ] login from my.proudcity.com
- [ ] login redirect
- [x] Responsive imgs
- [x] Login
- [x] Are previous hotfixes still applied ? #267
- [x] Gravityforms
- [x] Search
- [ ] Setup, submit xmlsitemaps for KP, Danvers, verify they are submitted
- [x] Service Center on Firebase (service-center-beta.proudcity.com)
- [x] Danvers hotjar code #960

**Comment by jlyon** [comment]
pushed, posted, sent @aschmoe @kevindherman @lukefretwell
